version: "3"

services:
  app:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    env_file:
      - .envs/django.env
    ports:
      - 8000:8000

  postgres:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .envs/postgres.env

volumes:
  pgdata:
  