version: "3"

services:
  app:
    build:
      context: .
    image: volley_graphql_app:1.0
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./app:/app/
    env_file:
      - .envs/django.env
    ports:
      - 8001:8001
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .envs/postgres.env

volumes:
  pgdata:
  app: